import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/your-first-generative-program',
        'tutorials/streaming-and-async',
        'tutorials/using-generative-stubs',
        'tutorials/making-agents-reliable',
        'tutorials/mifying-legacy-code',
        'tutorials/streaming-validation',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/generative-programming',
        'concepts/generative-functions',
        'concepts/instruct-validate-repair',
        'concepts/requirements-system',
        'concepts/architecture-vs-agents',
        'concepts/context-and-sessions',
        'concepts/mobjects-and-mify',
        'concepts/plugins',
      ],
    },
    {
      type: 'category',
      label: 'How-To',
      items: [
        'how-to/generative-functions',
        'how-to/tools-and-agents',
        'how-to/working-with-data',
        'how-to/backends-and-configuration',
        'how-to/act-and-aact',
        'how-to/m-decompose',
        'how-to/use-async-and-streaming',
        'how-to/use-context-and-sessions',
        'how-to/enforce-structured-output',
        'how-to/write-custom-verifiers',
        'how-to/evaluate-with-llm-as-a-judge',
        'how-to/configure-model-options',
        'how-to/use-images-and-vision',
        'how-to/build-a-rag-pipeline',
        'how-to/safety-guardrails',
        'how-to/refactor-prompts-with-cli',
        'how-to/unit-test-generative-code',
        'how-to/handling-exceptions',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/index',
        'examples/data-extraction-pipeline',
        'examples/legacy-code-integration',
        'examples/resilient-rag-fallback',
        'examples/traced-generation-loop',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/ollama',
        'integrations/huggingface',
        'integrations/openai',
        'integrations/vertex-ai',
        'integrations/bedrock',
        'integrations/watsonx',
        'integrations/mcp',
        'integrations/langchain',
        'integrations/smolagents',
        'integrations/m-serve',
      ],
    },
    {
      type: 'category',
      label: 'Observability',
      items: [
        'observability/telemetry',
        'observability/tracing',
        'observability/metrics',
        'observability/logging',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/intrinsics',
        'advanced/lora-and-alora-adapters',
        'advanced/prefix-caching-and-kv-blocks',
        'advanced/inference-time-scaling',
        'advanced/mellea-core-internals',
        'advanced/template-formatting',
        'advanced/custom-components',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contributing-guide',
        'community/building-extensions',
        'community/code-of-conduct',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting/common-errors',
        'troubleshooting/faq',
      ],
    },
  ],
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],
};

export default sidebars;
